name: Build & Test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build (Debug)
        run: dotnet build -c Debug

      - name: Build (Release)
        run: dotnet build -c Release

      - name: Test (Debug)
        run: dotnet test -c Debug --no-build

      - name: Test (Release)
        run: dotnet test -c Release --no-build
